-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.campaign_approved_assets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  campaign_id uuid NOT NULL,
  store_id uuid NOT NULL,
  asset_kind text NOT NULL CHECK (asset_kind = ANY (ARRAY['post_image'::text, 'reels_cover'::text, 'reels_video'::text])),
  approval_status text NOT NULL DEFAULT 'approved'::text CHECK (approval_status = ANY (ARRAY['approved'::text, 'superseded'::text])),
  approved_at timestamp with time zone NOT NULL DEFAULT now(),
  approved_by uuid,
  storage_bucket text NOT NULL,
  storage_path text NOT NULL,
  public_url_legacy text,
  generation_source text NOT NULL,
  campaign_snapshot jsonb NOT NULL,
  visual_snapshot jsonb,
  brand_profile_version integer,
  brand_profile_snapshot jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT campaign_approved_assets_pkey PRIMARY KEY (id),
  CONSTRAINT campaign_approved_assets_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id),
  CONSTRAINT campaign_approved_assets_campaign_store_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT campaign_approved_assets_campaign_store_fkey FOREIGN KEY (store_id) REFERENCES public.campaigns(id),
  CONSTRAINT campaign_approved_assets_campaign_store_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(store_id),
  CONSTRAINT campaign_approved_assets_campaign_store_fkey FOREIGN KEY (store_id) REFERENCES public.campaigns(store_id),
  CONSTRAINT campaign_approved_assets_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id)
);
CREATE TABLE public.campaign_branches (
  campaign_id uuid NOT NULL,
  branch_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT campaign_branches_pkey PRIMARY KEY (campaign_id, branch_id),
  CONSTRAINT campaign_branches_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT campaign_branches_branch_id_fkey FOREIGN KEY (branch_id) REFERENCES public.store_branches(id)
);
CREATE TABLE public.campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  store_id uuid NOT NULL,
  product_name text NOT NULL,
  price numeric,
  audience text,
  objective text CHECK (objective IS NULL OR (objective = ANY (ARRAY['promocao'::text, 'novidade'::text, 'queima'::text, 'sazonal'::text, 'reposicao'::text, 'combo'::text, 'engajamento'::text, 'visitas'::text, 'informativo'::text, 'institucional'::text, 'autoridade'::text]))),
  image_url text,
  headline text,
  body_text text,
  cta text,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'ready'::text, 'approved'::text])),
  created_at timestamp without time zone DEFAULT now(),
  ai_text text,
  ai_caption text,
  ai_hashtags text,
  ai_cta text,
  ai_generated_at timestamp with time zone,
  reels_hook text,
  reels_script text,
  reels_shotlist jsonb,
  reels_on_screen_text jsonb,
  reels_audio_suggestion text,
  reels_duration_seconds integer,
  reels_caption text,
  reels_cta text,
  reels_hashtags text,
  reels_generated_at timestamp with time zone,
  product_positioning text,
  description text,
  content_type text DEFAULT 'product'::text CHECK (content_type = ANY (ARRAY['product'::text, 'service'::text, 'info'::text])),
  product_image_url text,
  origin text NOT NULL DEFAULT 'manual'::text CHECK (origin = ANY (ARRAY['manual'::text, 'plan'::text])),
  weekly_plan_item_id uuid,
  campaign_type text NOT NULL DEFAULT 'both'::text CHECK (campaign_type = ANY (ARRAY['post'::text, 'reels'::text, 'both'::text])),
  post_status text NOT NULL DEFAULT 'none'::text CHECK (post_status = ANY (ARRAY['none'::text, 'draft'::text, 'ready'::text, 'approved'::text])),
  reels_status text NOT NULL DEFAULT 'none'::text CHECK (reels_status = ANY (ARRAY['none'::text, 'draft'::text, 'ready'::text, 'approved'::text])),
  price_label text,
  brand_dna_snapshot jsonb,
  layout_snapshot jsonb,
  layout_suggestion jsonb,
  domain_input jsonb NOT NULL DEFAULT '{}'::jsonb,
  domain_input_version integer NOT NULL DEFAULT 1,
  legacy_content_type text,
  visual_signature_id uuid,
  visual_context text DEFAULT 'standard'::text CHECK (visual_context = ANY (ARRAY['standard'::text, 'promotional'::text, 'seasonal'::text, 'premium'::text, 'urgency'::text])),
  CONSTRAINT campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT campaigns_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id),
  CONSTRAINT campaigns_weekly_plan_item_id_fkey FOREIGN KEY (weekly_plan_item_id) REFERENCES public.weekly_plan_items(id),
  CONSTRAINT campaigns_visual_signature_id_fkey FOREIGN KEY (visual_signature_id) REFERENCES public.visual_signatures(id)
);
CREATE TABLE public.feedback_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid NOT NULL,
  store_id uuid NOT NULL,
  page_path text,
  step text,
  attempt text,
  result text,
  would_help_sales text,
  improvement text,
  would_post text,
  reason_not_post text,
  score integer CHECK (score >= 0 AND score <= 10),
  allow_contact boolean DEFAULT false,
  user_agent text,
  campaign_id uuid,
  CONSTRAINT feedback_messages_pkey PRIMARY KEY (id),
  CONSTRAINT feedback_messages_user_fk FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT feedback_messages_store_fk FOREIGN KEY (store_id) REFERENCES public.stores(id),
  CONSTRAINT feedback_messages_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id)
);
CREATE TABLE public.generation_feedback (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid NOT NULL,
  store_id uuid NOT NULL,
  campaign_id uuid,
  weekly_plan_id uuid,
  page_path text,
  content_type text NOT NULL CHECK (content_type = ANY (ARRAY['campaign'::text, 'reels'::text, 'weekly_plan'::text, 'weekly_strategy'::text])),
  vote text NOT NULL CHECK (vote = ANY (ARRAY['yes'::text, 'maybe'::text, 'no'::text])),
  reason text,
  would_post text,
  user_agent text,
  CONSTRAINT generation_feedback_pkey PRIMARY KEY (id),
  CONSTRAINT generation_feedback_user_fk FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT generation_feedback_store_fk FOREIGN KEY (store_id) REFERENCES public.stores(id),
  CONSTRAINT generation_feedback_campaign_fk FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT generation_feedback_weekly_plan_fk FOREIGN KEY (weekly_plan_id) REFERENCES public.weekly_plans(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text,
  is_admin boolean DEFAULT false,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.store_branches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  store_id uuid NOT NULL,
  name text NOT NULL CHECK (length(TRIM(BOTH FROM name)) > 0),
  address text,
  neighborhood text,
  city text,
  state text,
  whatsapp text,
  is_main boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT store_branches_pkey PRIMARY KEY (id),
  CONSTRAINT store_branches_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id)
);
CREATE TABLE public.store_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  store_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text NOT NULL DEFAULT 'owner'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT store_members_pkey PRIMARY KEY (id),
  CONSTRAINT store_members_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id),
  CONSTRAINT store_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.stores (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  city text,
  state text,
  logo_url text,
  created_at timestamp without time zone DEFAULT now(),
  brand_positioning text,
  main_segment text,
  tone_of_voice text,
  address text,
  neighborhood text,
  phone text,
  whatsapp text,
  instagram text,
  primary_color text,
  secondary_color text,
  owner_user_id uuid NOT NULL,
  updated_at timestamp with time zone DEFAULT now(),
  brand_profile jsonb,
  brand_profile_version integer NOT NULL DEFAULT 1,
  brand_profile_updated_at timestamp with time zone,
  CONSTRAINT stores_pkey PRIMARY KEY (id),
  CONSTRAINT stores_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.visual_preference_learned (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  store_id uuid NOT NULL,
  revision integer NOT NULL DEFAULT 1,
  consolidated_at timestamp with time zone NOT NULL DEFAULT now(),
  signal_origin jsonb NOT NULL,
  preference jsonb NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT visual_preference_learned_pkey PRIMARY KEY (id),
  CONSTRAINT visual_preference_learned_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id)
);
CREATE TABLE public.visual_reader_cache (
  cache_key text NOT NULL,
  image_url text NOT NULL,
  product_name text NOT NULL,
  content_type text NOT NULL CHECK (content_type = ANY (ARRAY['product'::text, 'service'::text, 'message'::text])),
  profile jsonb NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT visual_reader_cache_pkey PRIMARY KEY (cache_key)
);
CREATE TABLE public.visual_signature_profiles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  signature_id uuid NOT NULL,
  context_type text NOT NULL CHECK (context_type = ANY (ARRAY['standard'::text, 'promotional'::text, 'seasonal'::text, 'premium'::text, 'urgency'::text])),
  composition_rules jsonb DEFAULT '{}'::jsonb,
  typography_rules jsonb DEFAULT '{}'::jsonb,
  color_rules jsonb DEFAULT '{}'::jsonb,
  intensity_level text NOT NULL DEFAULT 'balanced'::text CHECK (intensity_level = ANY (ARRAY['minimal'::text, 'balanced'::text, 'strong'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT visual_signature_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT visual_signature_profiles_signature_id_fkey FOREIGN KEY (signature_id) REFERENCES public.visual_signatures(id)
);
CREATE TABLE public.visual_signatures (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  store_id uuid NOT NULL UNIQUE,
  primary_color text NOT NULL DEFAULT '#6366f1'::text,
  secondary_color text NOT NULL DEFAULT '#8b5cf6'::text,
  logo_url text,
  store_name_typography jsonb DEFAULT '{"font": "Sora", "weight": "700"}'::jsonb,
  signature_seed text NOT NULL DEFAULT (uuid_generate_v4())::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT visual_signatures_pkey PRIMARY KEY (id),
  CONSTRAINT visual_signatures_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id)
);
CREATE TABLE public.weekly_plan_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  plan_id uuid NOT NULL,
  day_of_week integer NOT NULL CHECK (day_of_week >= 1 AND day_of_week <= 7),
  content_type text NOT NULL CHECK (content_type = ANY (ARRAY['post'::text, 'reels'::text])),
  theme text NOT NULL,
  recommended_time text,
  campaign_id uuid,
  brief jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'ready'::text, 'approved'::text])),
  target_content_type text,
  target_domain_input jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT weekly_plan_items_pkey PRIMARY KEY (id),
  CONSTRAINT weekly_plan_items_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.weekly_plans(id),
  CONSTRAINT weekly_plan_items_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id)
);
CREATE TABLE public.weekly_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  store_id uuid NOT NULL,
  week_start date NOT NULL CHECK (EXTRACT(isodow FROM week_start) = 1::numeric),
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'approved'::text])),
  strategy jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT weekly_plans_pkey PRIMARY KEY (id),
  CONSTRAINT weekly_plans_store_id_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id)
);